# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Latch Creative
logo: latch-creative-logo.png
splash_image: splash.jpeg
email: 
description: > # this means to ignore newlines until "baseurl:"
  Latch Creative is a creative agency that builds awesome projects for
  awesome companies. We develop mobile apps, websites and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://latchcreative.co" # the base hostname & protocol for your site
twitter_username: 
github_username:  latch-creative

# Build settings
markdown: kramdown
